### ISSUE TITLE
Naturally fails to compare strings with letters

### ISSUE THREAD

**Issue by zedalaye** [dogweather/naturally#14]
Naturally 1.3.2 fails to sort this simple array ['A', '1'] while 1.3.1 can.

```ruby
[pierre@azubuntu naturally (master)]$ irb
irb(main):001:0> RUBY_VERSION
=> "2.1.5"
irb(main):002:0> require 'naturally'
=> true
irb(main):003:0> Naturally.sort(['A', '1'])
ArgumentError: comparison of Array with Array failed
	from /home/pierre/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/naturally-1.3.2/lib/naturally.rb:16:in `sort_by'
	from /home/pierre/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/naturally-1.3.2/lib/naturally.rb:16:in `sort'
	from (irb):3
	from /home/pierre/.rbenv/versions/2.1.5/bin/irb:11:in `<main>'
```
I narrowed down the problem to ruby <=> :

```ruby
irb(main):009:0> Naturally.normalize('A') <=> Naturally.normalize('1')
=> nil
irb(main):012:0> [['A']] <=> [[2]]
=> nil
irb(main):010:0> ['A'] <=> [2]
=> nil
```

**Comment by zedalaye** [comment]
It works (and all specs passes) if I change `Segment#<=>` to :

```ruby
module Naturally
  class Segment

    def <=>(other)
      cmp = 0
      other_array = other.to_array
      to_array.each_with_index do |e, index|
        if index < other_array.length
          cmp = e <=> other_array[index]
          # The key is to make Integers comparable with Strings
          cmp = (e.is_a?(Integer)) ? -1 : 1 unless cmp
          break if cmp != 0
        else
          # "Longer" strings are "Higher" than shorter ones
          cmp = 1
          break
        end
      end
      cmp
    end

  end
end
```

**Comment by zedalaye** [comment]
I have found another more magical hack to achieve the same and make sure Segment arrays starting with an Integer can always been compared to another Segment array starting with a String (all specs passes too...) by adding a (subtly crafted) prefix to Segment arrays:

```ruby
module Naturally
  # An entity which can be compared to other like elements for
  # sorting. It's an object representing
  # a value which implements the {Comparable} interface.
  class Segment
    include Comparable

    def initialize(v)
      @val = v
    end

    def <=>(other)
      to_array <=> other.to_array
    end

    # @return [Array] a representation of myself in array form
    #                 which enables me to be compared against
    #                 another instance for sorting.
    #                 The array is prepended with a symbol so
    #                 two arrays are always comparable.
    #
    # @example a simple number
    #   Segment.new('10').to_array #=> [:int, 10]
    #
    # @example a college course code
    #   Segment.new('MATH101').to_array #=> [:str, "MATH", 101]
    #
    # @example Section 633a of the ADEA
    #   Segment.new('633a').to_array #=> [:int, 633, "a"]
    def to_array
      # TODO: Refactor, probably via polymorphism
      if @val =~ /^(\p{Digit}+)(\p{Alpha}+)$/
        [:int, $1.to_i, $2]
      elsif @val =~ /^(\p{Alpha}+)(\p{Digit}+)$/
        [:str, $1, $2.to_i]
      elsif @val =~ /^\p{Digit}+$/
        [:int, @val.to_i]
      else
        [:str, @val]
      end
    end
  end
end
```
It works because :int < :str and so [:int, 1] <=> [:str, 'a'] = -1
