### ISSUE TITLE
Encoding::CompatibilityError

### ISSUE THREAD

**Issue by bibendi** [dogweather/naturally#17]
After upgrade to 1.3.2

```
$ irb
> require 'naturally'
=> true
> Naturally.sort(['мама', 'мыла', 'раму'])
Encoding::CompatibilityError: incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:40:in `scan'
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:40:in `normalize'
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:16:in `block in sort'
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:16:in `each'
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:16:in `sort_by'
	from /home/merkushin/.rvm/gems/ruby-1.9.3-p545/gems/naturally-1.3.2/lib/naturally.rb:16:in `sort'
	from (irb):2

```

**Comment by dogweather** [comment]
I'm sorry, ruby 1.9 isn't supported.
